services:
  app:
    build:
      context: .
      target: final
    image: krre/blog-api:v1.1
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - RUST_LOG=info
    ports:
      - 127.0.0.1:4010:3000
